// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCni_l1OHfipG6QlMG1qKRQxqVYDMdbm0U',
    appId: '1:1065323736168:web:c7f43062f71524bd89dfdd',
    messagingSenderId: '1065323736168',
    projectId: 'alphagymanstic-front',
    authDomain: 'alphagymanstic-front.firebaseapp.com',
    storageBucket: 'alphagymanstic-front.appspot.com',
    measurementId: 'G-1MQCDMZSQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5z_CkfKhS67DVSQAeTv28k1oTqEPQ2K0',
    appId: '1:1065323736168:android:842b36f77f78b61b89dfdd',
    messagingSenderId: '1065323736168',
    projectId: 'alphagymanstic-front',
    storageBucket: 'alphagymanstic-front.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBgTYOxTy1cfvcYO7-6mop901o4S3PUfc',
    appId: '1:1065323736168:ios:d677bfde2a87cf8689dfdd',
    messagingSenderId: '1065323736168',
    projectId: 'alphagymanstic-front',
    storageBucket: 'alphagymanstic-front.appspot.com',
    iosBundleId: 'com.example.alphaGymnasticCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBgTYOxTy1cfvcYO7-6mop901o4S3PUfc',
    appId: '1:1065323736168:ios:d677bfde2a87cf8689dfdd',
    messagingSenderId: '1065323736168',
    projectId: 'alphagymanstic-front',
    storageBucket: 'alphagymanstic-front.appspot.com',
    iosBundleId: 'com.example.alphaGymnasticCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCni_l1OHfipG6QlMG1qKRQxqVYDMdbm0U',
    appId: '1:1065323736168:web:50318cf71d28014089dfdd',
    messagingSenderId: '1065323736168',
    projectId: 'alphagymanstic-front',
    authDomain: 'alphagymanstic-front.firebaseapp.com',
    storageBucket: 'alphagymanstic-front.appspot.com',
    measurementId: 'G-XNF42X1HTQ',
  );
}
